version: '3.8'

services:
  app:
    build:
      context: ./web-app
    ports:
      - "8080:80"
    volumes:
      - ./web-app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: contra
      MYSQL_DATABASE: proy
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      # Carga del sql
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

volumes:
  db-data: